run:
  deadline: 5m
  issues-exit-code: 1
  skip-dirs: vendor
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
linters:
  enable:
    # Sorted alphabetically.
    - deadcode
    - errcheck
    - goconst
    - godot
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unparam
    - unused
    - varcheck
    - exportloopref

linters-settings:
  errcheck:
    exclude: ./.errcheck_excludes.txt
  misspell:
    locale: US
  goconst:
    min-occurrences: 5

#issues:
#  exclude-rules:
#    # These are not being checked since these methods exist
#    # so that no one else could implement them.
#    - linters:
#        - unused
#      text: "SourceStoreAPI.implementsStoreAPI"
#    - linters:
#        - unused
#      text: "SourceStoreAPI.producesBlocks"
#    - linters:
#        - unused
#      text: "Source.producesBlocks"
#    - linters:
#        - unused
#      text: "newMockAlertmanager"
#    - linters:
#        - unused
#      text: "ruleAndAssert"
